export var Projects = [
  {
    title: 'Blog manager',
    year: 2020,
    image: 'angular',
    description: 'Blog that allows you to add news, recieve visitors comments',
    liveLink: 'github.com',
    codeLink: 'https://github.com/JasonAlvarado/',
    stack: '.NET Core + Angular',
  },
  {
    title: 'To do app',
    year: 2020,
    image: 'react',
    description: 'Simple to do app',
    liveLink: 'github.com',
    codeLink: 'github.com',
    stack: '.NET Framework + Angular',
  },
  {
    title: 'Forum',
    year: 2020,
    image: 'net-core',
    description: 'Forum app based on Reddit',
    liveLink: 'github.com',
    codeLink: 'github.com',
    stack: '.NET Framework + Angular',
  },
  {
    title: 'Library',
    year: 2020,
    image: 'mongo-db',
    description:
      'This library app allows you to loan and buy books. See statistics and export sell reports',
    liveLink: 'github.com',
    codeLink: 'github.com',
    stack: 'MEAN',
  },
  {
    title: 'Discord Bot',
    year: 2020,
    image: 'node-js',
    description: 'Discord bot that send a message to play videogames',
    liveLink: 'github.com',
    codeLink: 'github.com',
    stack: 'Node Js',
  },
  {
    title: 'Hotel app',
    year: 2020,
    image: 'bootstrap',
    description: 'This app was created to reserve hotels, it use a public API',
    liveLink: 'github.com',
    codeLink: 'github.com',
    stack: 'MERN',
  },
];
