export var Projects = [
  {
    title: 'Blog manager',
    year: 2020,
    image: 'blog',
    description: 'Blog that allows you to add news, recieve visitors comments',
    liveLink: '#',
    codeLink: 'https://#/JasonAlvarado/',
    stack: '.NET Core + Angular',
  },
  {
    title: 'To do app',
    year: 2020,
    image: 'to-do',
    description: 'Simple to do app',
    liveLink: '#',
    codeLink: '#',
    stack: '.NET Framework + Angular',
  },
  {
    title: 'Forum',
    year: 2020,
    image: 'forum',
    description: 'Forum app based on Reddit',
    liveLink: '#',
    codeLink: '#',
    stack: '.NET Framework + Angular',
  },
  {
    title: 'Library',
    year: 2020,
    image: 'library',
    description:
      'This library app allows you to loan and buy books. See statistics and export sell reports',
    liveLink: '#',
    codeLink: '#',
    stack: 'MEAN',
  },
  {
    title: 'Discord Bot',
    year: 2020,
    image: 'discord',
    description: 'Discord bot that send a message to play videogames',
    liveLink: '#',
    codeLink: '#',
    stack: 'Node Js',
  },
  {
    title: 'Hotel app',
    year: 2020,
    image: 'hotel',
    description: 'This app was created to reserve hotels, it use a public API',
    liveLink: '#',
    codeLink: '#',
    stack: 'MERN',
  },
];
